version: '3.8'

services:
  postgres:
    container_name: tbc_project-postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: collabdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: JordiSnake
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  django_backend:
    container_name: django_backend
    build:
      context: ./django_backend
      dockerfile: django.dockerfile
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=False
      - DB_NAME=collabdb
      - DB_USER=postgres
      - DB_PASSWORD=JordiSnake
      - DB_HOST=postgres
      - DB_PORT=5432
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 cfcollab.wsgi:application"
    expose:
      - "8000"
    depends_on:
      - postgres
    networks:
      - app-network

  react_frontend:
    container_name: react_frontend
    build:
      context: ./react_frontend
      dockerfile: react.dockerfile
    environment:
      - VITE_BACKEND_URL=https://sergidevops.com/api
    expose:
      - "80"
    depends_on:
      - django_backend
    networks:
      - app-network

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - react_frontend
      - django_backend
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge
